###### TODO: how use exact version specifiers for all packages ######
name: streamlit-env
channels:
  - conda-forge
dependencies:
  - python==3.10
  - plotly==5.18.0
  - pip==23.3
  - numpy==1.25.2
  - pandas==2.1.2
  - mono==6.12.0.90
  - pip: # dependencies only available through pip
      # streamlit dependencies
    - streamlit==1.34.0
    - streamlit-plotly-events==0.0.6
    - streamlit-aggrid==0.3.4.post3
    - captcha==0.5.0
