###### TODO: how use exact version specifiers for all packages ######
name: streamlit-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - plotly
  - pip
  - pip: # dependencies only available through pip
      # streamlit dependencies
    - streamlit
    - streamlit-plotly-events
    - streamlit-aggrid

# Notes:
# - pandas and numpy are installed through pyopenms
# - mono is installed through ThermoRawFileParser which is installed through openms-thirdparty