name: streamlit-env
dependencies:
  - python=3.10
  - pip
  - pip:
      - altair==5.5.0
      - attrs==25.3.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - captcha==0.5.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.56.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - idna==3.10
      - jinja2==3.1.6
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - narwhals==1.32.0
      - numpy==1.26.4
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - plotly==5.22.0
      - protobuf==5.29.4
      - psutil==7.0.0
      - pyarrow==19.0.1
      - pydeck==0.9.1
      - pyopenms==3.2.0
      - pyopenms-viz==1.0.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - referencing==0.36.2
      - requests==2.32.3
      - rpds-py==0.24.0
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.43.0
      - streamlit-js-eval==0.1.7
      - tenacity==9.0.0
      - toml==0.10.2
      - tornado==6.4.2
      - typing-extensions==4.13.0
      - tzdata==2025.2
      - urllib3==2.3.0
      - watchdog==6.0.0
