###### TODO: how use exact version specifiers for all packages ######
name: streamlit-env
channels:
  - conda-forge
dependencies:
  - python==3.11
  - plotly==5.22.0
  - pip==24.0
  - numpy==1.26.4 # pandas and numpy are dependencies of pyopenms, however, pyopenms needs numpy<=1.26.4
  - mono==6.12.0.90
  - pip: # dependencies only available through pip
      # streamlit dependencies
    - streamlit>=1.38.0
    - captcha==0.5.0
    - pyopenms_viz>=0.1.2
