###### TODO: how use exact version specifiers for all packages ######
name: streamlit-env
channels:
   - conda-forge
   - bioconda
dependencies:
   - python==3.11
   - plotly==5.22.0
   - pip==24.0
   - numpy==1.26.4 # pandas and numpy are dependencies of pyopenms, however, pyopenms needs numpy<=1.26.4
   - pandas==2.2.1 # Adding pandas with specific version for better compatibility
   - pytest==8.0.0 # Adding pytest for running tests

   - pip:
        # dependencies only available through pip
        # streamlit dependencies
        - streamlit>=1.38.0
        - captcha==0.5.0
        - pyopenms==3.2.0
        - pyopenms_viz==1.0.0
        - streamlit-js-eval
