apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: nodeselector.yaml
    target:
      kind: Deployment
  - path: streamlit-resources.yaml
    target:
      kind: Deployment
      name: streamlit
  - path: worker-resources.yaml
    target:
      kind: Deployment
      name: rq-worker
