apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: template-app-

commonLabels:
  app: template-app

images:
  - name: openms-streamlit
    newName: ghcr.io/openms/streamlit-template
    newTag: main-full

patches:
  - target:
      kind: IngressRoute
      name: streamlit-traefik
    patch: |
      - op: replace
        path: /spec/routes/0/match
        value: Host(`template.webapps.openms.de`) && PathPrefix(`/`)
      - op: replace
        path: /spec/routes/0/services/0/name
        value: template-app-streamlit
  - target:
      kind: Deployment
      name: streamlit
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "redis://template-app-redis:6379/0"
  - target:
      kind: Deployment
      name: rq-worker
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "redis://template-app-redis:6379/0"
