apiVersion: v1
kind: ConfigMap
metadata:
  name: streamlit-config
data:
  settings-overrides.json: |
    {
      "online_deployment": true,
      "demo_workspaces": {
        "enabled": true,
        "source_dirs": ["/workspaces-streamlit-template/.demos"]
      }
    }
