apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openms

resources:
  - namespace.yaml
  - configmap.yaml
  - redis.yaml
  - workspace-pvc.yaml
  - streamlit-deployment.yaml
  - streamlit-service.yaml
  - rq-worker-deployment.yaml
  - traefik-ingressroute.yaml
  - cleanup-cronjob.yaml
