#!/bin/bash
# Assemble the macOS .app bundle from the relocatable Python, the shared app
# payload, the OpenMS binaries/libraries/data, and the icon. Run from the repo
# root. Expects these to already exist in the working directory:
#   python/        relocatable interpreter (python-build-standalone, install_only)
#   openms-bin/    TOPP tool binaries + their dylibs (from the OpenMS package)
#   openms-lib/    OpenMS runtime libraries
#   share/         OpenMS data directory (contains share/OpenMS, incl. THIRDPARTY)
#   AppIcon.icns   generated by make_icns.sh
#
# Required environment: APP_NAME, BUNDLE_ID, VERSION.
set -euo pipefail

APP_NAME="${APP_NAME:?APP_NAME is required}"
BUNDLE_ID="${BUNDLE_ID:?BUNDLE_ID is required}"
VERSION="${VERSION:-0.0.0}"

HERE="$(cd "$(dirname "$0")" && pwd)"   # installer/macos
APP="dist/${APP_NAME}.app"
RES="$APP/Contents/Resources"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$RES"

# 1. Shared application payload (src, content, assets, app.py, settings.json, ...).
python3 installer/common/collect_payload.py "$RES"

# 2. Platform-specific pieces.
cp -R python "$RES/python"
cp -R openms-bin "$RES/bin"
cp -R openms-lib "$RES/lib"
cp -R share "$RES/share"
cp AppIcon.icns "$RES/AppIcon.icns"

# 3. Streamlit config: drop the 0.0.0.0 bind address so the app serves on
#    localhost (mirrors the Windows build), and disable the first-run email prompt.
if [ -f "$RES/.streamlit/config.toml" ]; then
    grep -v '^address' "$RES/.streamlit/config.toml" > "$RES/.streamlit/config.toml.tmp"
    mv "$RES/.streamlit/config.toml.tmp" "$RES/.streamlit/config.toml"
fi
mkdir -p "$RES/.streamlit"
printf '[general]\nemail = ""\n' > "$RES/.streamlit/credentials.toml"

# 4. Info.plist + launcher from templates (use '|' delimiter; values are simple).
sed -e "s|@APP_NAME@|${APP_NAME}|g" \
    -e "s|@BUNDLE_ID@|${BUNDLE_ID}|g" \
    -e "s|@VERSION@|${VERSION}|g" \
    "$HERE/Info.plist.template" > "$APP/Contents/Info.plist"

sed -e "s|@APP_NAME@|${APP_NAME}|g" \
    "$HERE/launcher.sh.template" > "$APP/Contents/MacOS/${APP_NAME}"
chmod +x "$APP/Contents/MacOS/${APP_NAME}"

echo "Built $APP"
