name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-full-app:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build the full Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        tags: streamlitapp:latest
        load: true
        cache-from: type=gha,scope=full-app
        cache-to: type=gha,mode=max,scope=full-app

  build-simple-app:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build the Docker image (pyOpenMS only)
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile_simple
        tags: streamlitapp-simple:latest
        load: true
        cache-from: type=gha,scope=simple-app
        cache-to: type=gha,mode=max,scope=simple-app